# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ksbuilder < Formula
  desc ""
  homepage "https://github.com/kubesphere/ksbuilder"
  version "0.4.5"

  on_macos do
    url "https://github.com/kubesphere/ksbuilder/releases/download/v0.4.5/ksbuilder_0.4.5_darwin_all.tar.gz"
    sha256 "1eba4849a68866c7f4e6e1c9c13585255d11e3c1294bb5baee60b8c7d25272d2"

    def install
      bin.install "ksbuilder"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubesphere/ksbuilder/releases/download/v0.4.5/ksbuilder_0.4.5_linux_amd64.tar.gz"
        sha256 "b8a7b6032b9b7af9e32391ad17cc0c7a385af28917b38bd3f8177b1f42d1eb50"

        def install
          bin.install "ksbuilder"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubesphere/ksbuilder/releases/download/v0.4.5/ksbuilder_0.4.5_linux_arm64.tar.gz"
        sha256 "c075fba9228240bbb62d4d5af6d38c0866e7c913ab820f5af9e336c1b47ff14c"

        def install
          bin.install "ksbuilder"
        end
      end
    end
  end
end
