# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ksbuilder < Formula
  desc ""
  homepage "https://github.com/kubesphere/ksbuilder"
  version "0.3.6"

  on_macos do
    url "https://github.com/kubesphere/ksbuilder/releases/download/v0.3.6/ksbuilder_0.3.6_darwin_all.tar.gz"
    sha256 "e0244fe9512dfcca53b22e68c35ad11a26331c086f94cc031897dabf7a35db50"

    def install
      bin.install "ksbuilder"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubesphere/ksbuilder/releases/download/v0.3.6/ksbuilder_0.3.6_linux_arm64.tar.gz"
      sha256 "5b4f17d66262adda8d66086989b341f4f7c6f0df6b391307df67337e61bac139"

      def install
        bin.install "ksbuilder"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubesphere/ksbuilder/releases/download/v0.3.6/ksbuilder_0.3.6_linux_amd64.tar.gz"
      sha256 "c1870c13b8bd37694276a1e7af20ca011cf7a4e331096ae02dd165264994b151"

      def install
        bin.install "ksbuilder"
      end
    end
  end
end
