# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ksbuilder < Formula
  desc ""
  homepage "https://github.com/kubesphere/ksbuilder"
  version "0.3.3"

  on_macos do
    url "https://github.com/kubesphere/ksbuilder/releases/download/v0.3.3/ksbuilder_0.3.3_darwin_all.tar.gz"
    sha256 "a68d10f8590cc747192762b351b003efcea3eedde72ada8f796116b436b0460e"

    def install
      bin.install "ksbuilder"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubesphere/ksbuilder/releases/download/v0.3.3/ksbuilder_0.3.3_linux_arm64.tar.gz"
      sha256 "b396ae57e10007c23b4c849553b0b380be7bc00e6c667fe5aa20921c6a159027"

      def install
        bin.install "ksbuilder"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubesphere/ksbuilder/releases/download/v0.3.3/ksbuilder_0.3.3_linux_amd64.tar.gz"
      sha256 "c81eef915ba0fb3c822f3fccab4665ca3d9658c4dfef877397b4832ded972c11"

      def install
        bin.install "ksbuilder"
      end
    end
  end
end
